on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: ubuntu-latest

    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test