on:
  workflow_dispatch:

jobs:
  example_matrix:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: node-app

    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm test
      - run: npm 