name: Push & Pull request

# Create two jobs inside a new workflow
# When you have a push, execute both job
# When you have a PR, execute only the first job.

on:
  push:

jobs:
  print-event:
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)

  print-event-2:
    if: github.event_name == 'push'
    
    runs-on: ubuntu-latest

    steps:
      - name: Print the event that triggered this workflow
        run: |
          echo ${{ github.event_name }}

      - name: Print the current time
        run: |
          echo $(date)
